# Site settings
title: Clouds and Clocks
email: help@writer-theme.com
description: > # Writer Theme is a responsive template
 focussed on typography, minimal design and
  quality photography built using the Jekyll platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/jacob', 'fa-user']
single_footer: '<p>Jacob T. Nielsen &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']


# Build settings
markdown: kramdown
